//
// This is a generated file, do not edit!
// Generated by ConfigurationPlist, see https://github.com/417-72KI/ConfigurationPlist
//

import Foundation

struct AppConfig: Codable {
    static let `default`: AppConfig = .load()

    let aStruct: AStruct
    let bStruct: BStruct

    enum CodingKeys: String, CodingKey {
        case aStruct = "a_struct"
        case bStruct = "b_struct"
    }
}

private extension AppConfig {
    static func load() -> AppConfig {
        guard let filePath = Bundle.main.path(forResource: "Config", ofType: "plist") else { fatalError("Config.plist not found") }
        return load(from: filePath)
    }
}

extension AppConfig {
    static func load(from filePath: String) -> AppConfig {
        do {
            let data = try Data(contentsOf: URL(fileURLWithPath: filePath))
            return try PropertyListDecoder().decode(AppConfig.self, from: data)
        } catch {
            fatalError("\(filePath) is invalid. cause: \(error)")
        }
    }
}

extension AppConfig {
    struct AStruct: Codable {
    }
}

extension AppConfig {
    struct BStruct: Codable {
        let hoge: String

        enum CodingKeys: String, CodingKey {
            case hoge
        }
    }
}
