included:
  - BuildConfigSwiftDemo
excluded:
  - Libs
  - Pods
  - Carthage

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - closure_end_indentation
  - conditional_returns_on_newline
  - discouraged_object_literal
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - prefixed_toplevel_constant
  - strict_fileprivate
  - trailing_closure
  - unused_optional_binding

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length: 2

large_tuple:
  warning: 4
  error: 5

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  .*?
                    \/\/
                    \/\/  Created by .*? on \d{1,4}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} .*?\. All rights reserved\.
                    \/\/
