# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'BuildConfigSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuildConfigSwiftDemo
  pod 'SwiftLint'
  # pod 'BuildConfig.swift' # For CI build

  target 'BuildConfigSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
