name: BuildConfigSwiftDemo
attributes:
  ORGANIZATIONNAME: 417.72KI
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: false
    CLANG_ENABLE_OBJC_ARC: true
options:
  xcodeVersion: 10.2
  bundleIdPrefix: io.github.417-72KI
packages:
  XCGLogger:
    url: https://github.com/DaveWoodCom/XCGLogger
    from: 7.0.1
  # SwiftLint:
  #   url: https://github.com/realm/SwiftLint
  #   from: 0.53.0
targets:
  BuildConfigSwiftDemo:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources: 
      - BuildConfigSwiftDemo
      - path: Libs
        optional: true
      - path: Libs/BuildConfig_swift/BuildConfig.generated.swift
        optional: true
        createIntermediateGroups: true
    info:
      path: BuildConfigSwiftDemo/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: '6.0'
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: 
          - arm64
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        PRODUCT_NAME: BuildConfigSwiftDemo
        PRODUCT_BUNDLE_IDENTIFIER: io.github.417-72KI.BuildConfigSwiftDemo
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        LIBRARY_SEARCH_PATHS: $(inherited)
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
      configs:
        debug: 
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: ""
        release: 
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: ""
          EXCLUDED_SOURCE_FILE_NAMES: Mock*
    # buildToolPlugins:
    #   - plugin: SwiftLintPlugin
    #     package: SwiftLint
    preBuildScripts:
      - name: BuildConfig.swift
        script: |
          if [ "$ENABLE_PREVIEWS" == "YES" ]; then
            exit 0
          fi

          if [ "${CONFIGURATION}" = 'Release' ]; then
            ENVIRONMENT='production'
          elif [ "${CONFIGURATION}" = 'Staging' ]; then
            ENVIRONMENT='staging'
          elif [ "${CONFIGURATION}" = 'IntegrationTest' ]; then
            ENVIRONMENT='integration_test'
          else
            ENVIRONMENT='development'
          fi
          xcrun -sdk macosx swift run --package-path "${SRCROOT}/.." buildconfigswift -o ${SRCROOT}/Libs/BuildConfig_swift -e $ENVIRONMENT ${SRCROOT}/Resources/Config # For Development
        outputFiles:
          - $(SRCROOT)/Libs/BuildConfig_swift/BuildConfig.generated.swift
        basedOnDependencyAnalysis: false
    dependencies:
      - package: XCGLogger
  BuildConfigSwiftDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources: BuildConfigSwiftDemoTests
    info:
      path: BuildConfigSwiftDemoTests/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/BuildConfigSwiftDemo.app/BuildConfigSwiftDemo
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: iPhone Developer
      DEVELOPMENT_TEAM: ""
    dependencies:
      - target: BuildConfigSwiftDemo
