name: BuildConfigSwiftDemo
attributes:
  ORGANIZATIONNAME: 417.72KI
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: false
    CLANG_ENABLE_OBJC_ARC: true
options:
  xcodeVersion: 10.2
  bundleIdPrefix: io.github.417-72KI
packages:
  XCGLogger:
    url: https://github.com/DaveWoodCom/XCGLogger
    from: 7.0.1
  StubNetworkKit:
    url: https://github.com/417-72KI/StubNetworkKit.git
    from: 0.3.0
  # SwiftLint:
  #   url: https://github.com/realm/SwiftLint
  #   from: 0.53.0
  BuildConfig.Swift:
    path: ../
targets:
  BuildConfigSwiftDemo:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources: 
      - BuildConfigSwiftDemo
    info:
      path: BuildConfigSwiftDemo/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: '6.0'
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: 
          - arm64
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        PRODUCT_NAME: BuildConfigSwiftDemo
        PRODUCT_BUNDLE_IDENTIFIER: io.github.417-72KI.BuildConfigSwiftDemo
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        LIBRARY_SEARCH_PATHS: $(inherited)
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
      configs:
        debug: 
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: ""
        release: 
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: ""
          EXCLUDED_SOURCE_FILE_NAMES: Mock*
    buildToolPlugins:
      - plugin: BuildConfigSwiftGenerate
        package: BuildConfig.Swift
    #   - plugin: SwiftLintPlugin
    #     package: SwiftLint
    dependencies:
      - package: XCGLogger
  BuildConfigSwiftDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources: BuildConfigSwiftDemoTests
    info:
      path: BuildConfigSwiftDemoTests/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/BuildConfigSwiftDemo.app/BuildConfigSwiftDemo
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: iPhone Developer
      DEVELOPMENT_TEAM: ""
    dependencies:
      - target: BuildConfigSwiftDemo
      - package: StubNetworkKit
