name: Test
on:
  push:
    paths:
      - '**.swift'
      - '.github/workflows/test.yml'
  pull_request: {}
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Cache SPM build directory
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: test
        run: set -o pipefail && swift test
  